"""clerk identities replace passwords and sessions

Adding users.clerk_user_id as NOT NULL with no default fails loudly if any rows
exist, which is the correct outcome: a password-era account has no Clerk identity
to backfill, and inventing one would silently orphan it. Migrate those users in
Clerk first (or delete them) before running this.


Revision ID: b2709cdbfd2f
Revises: eeaa584dffd7
Create Date: 2026-09-03 14:43:00.838209

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'b2709cdbfd2f'
down_revision: str | None = 'eeaa584dffd7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_email_codes_user_id'), table_name='email_codes')
    op.drop_table('email_codes')
    op.add_column('users', sa.Column('clerk_user_id', sa.Text(), nullable=False))
    op.create_unique_constraint(None, 'users', ['clerk_user_id'])
    op.drop_column('users', 'email_verified_at')
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('email_verified_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'clerk_user_id')
    op.create_table('email_codes',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('code_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('attempts', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('email_codes_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('email_codes_pkey'))
    )
    op.create_index(op.f('ix_email_codes_user_id'), 'email_codes', ['user_id'], unique=False)
    op.create_table('sessions',
    sa.Column('token_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('sessions_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token_hash', name=op.f('sessions_pkey'))
    )
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###
