"""email verification codes

Revision ID: eeaa584dffd7
Revises: d4dead4c88c3
Create Date: 2026-09-01 12:50:32.088748

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'eeaa584dffd7'
down_revision: str | None = 'd4dead4c88c3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_email_codes_user_id', 'email_codes', ['user_id'], unique=False)
    op.add_column('users', sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###
    # Accounts that predate verification are grandfathered in -- they signed up when
    # no code existed, and would otherwise be locked out with no way to verify.
    op.execute("UPDATE users SET email_verified_at = now()")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_verified_at')
    op.drop_index('ix_email_codes_user_id', table_name='email_codes')
    op.drop_table('email_codes')
    # ### end Alembic commands ###
